
# Enabling Antigen https://github.com/zsh-users/antigen
source ~/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
# antigen bundle git
antigen bundles <<EOBUNDLES
  git
  colored-man-pages
  colorize
  cp
  iterm2
  screen
  systemadmin
  torrent
  zsh-navigation-tools
  djui/alias-tips
  zsh-users/zsh-completions
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-history-substring-search
EOBUNDLES
#  ssh-agent
#  chucknorris

antigen theme agnoster
#antigen theme history-substring-search
#antigen bundle zsh-autosuggestions
#antigen bundle vagrant
#antigen bundle nomad
#antigen bundle docker

# Python Plugins
#antigen bundle pip
#antigen bundle python
#antigen bundle virtualenv

# Load the theme.
# antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply

# Sourcing Theme configs
#source ~/git/DotFiles/zsh/custom_agnoster-theme.zsh

# Sourcing Aliases
source ~/git/DotFiles/zsh/aliases.zsh

# Sourcing Autojump settings
source ~/git/DotFiles/zsh/autojump.zsh

# Sourcing zstyle configs
source ~/git/DotFiles/zsh/zstyles.zsh

# Auto completion configs
source ~/git/DotFiles/zsh/completion.zsh

# Auto completion kustomize configs
source ~/git/DotFiles/zsh/kustomize_completion.zsh

# Sourcing setopt configs
source ~/git/DotFiles/zsh/setopt.zsh

# Sourcing ZSH mod configs
source ~/git/DotFiles/zsh/modules.zsh

# Sourcing ZSH functions
#source ~/git/DotFiles/zsh/functions.zsh

# Sourcing Key binding configs
source ~/git/DotFiles/zsh/key_bindings.zsh

# Sourcing some extra zsh configs
source ~/git/DotFiles/zsh/extra.zsh

# Sourcing installed plugins configs
source ~/git/DotFiles/zsh/plugins_configs.zsh

# Sourcing my custom ZSH variables
source ~/git/DotFiles/zsh/variables.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/manish/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/manish/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/manish/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/manish/google-cloud-sdk/completion.zsh.inc'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# bun completions
[ -s "/Users/manish/.bun/_bun" ] && source "/Users/manish/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

